package org.turbofinn.dbmappers;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.google.gson.Gson;
import lombok.*;
import org.turbofinn.aws.AWSCredentials;

import java.util.HashMap;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName = "Restaurant")
public class DB_Restaurant extends DB_DateTable{

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String restaurantId;
    String name;
    String address;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "city-index")
    String city;
    String state;
    String pincode;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "emailId-index")
    String emailId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "contactNo-index")
    String contactNo;
    String restaurantAccountNo;
    String tableCount;
    String logo;
    String status;
    @DynamoDBAttribute
    String cuisineTypes;
    String openingTime;
    String closingTime;
    Integer seatingCapacity;
    @DynamoDBAttribute
    String serviceTypes;

    Double latitude;
    Double longitude;

    String AccountNumber;
    String ifscCode;
    String accountHolderName;
    String bankName;




    public static enum ActionType {
        CREATE("CREATE"),
        UPDATE("UPDATE");
        private String text;

        private ActionType(String text) {
            this.text = text;
        }

        @Override
        public String toString() {
            return this.text;
        }

        public static DB_Restaurant.ActionType getActionType(String type) {
            if (type == null) {
                return null;
            }
            switch (type) {
                case "CREATE":
                    return DB_Restaurant.ActionType.CREATE;
                case "UPDATE":
                    return DB_Restaurant.ActionType.UPDATE;
                default:
                    return null;
            }
        }
    }

    public static enum StatusType {
        ACTIVE("Active"),
        INACTIVE("Inactive");
        private String text;

        private StatusType(String text) {
            this.text = text;
        }

        @Override
        public String toString() {
            return this.text;
        }

        public static DB_Restaurant.StatusType getStatusType(String type) {
            if (type == null) {
                return null;
            }
            switch (type) {
                case "ACTIVE":
                    return StatusType.ACTIVE;
                case "UPDATE":
                    return StatusType.INACTIVE;
                default:
                    return null;
            }
        }

    }

    public void save() {
        AWSCredentials.dynamoDBMapper().save(this);
        System.out.println("*** Restaurant Saved *** " + new Gson().toJson(this));
    }

    public static DB_Restaurant fetchRestaurantByID(String restaurantId){
        return (restaurantId == null) ? null : AWSCredentials.dynamoDBMapper().load(DB_Restaurant.class, restaurantId);
    }

    public static DB_Restaurant fetchRestaurantByMobileNo(String contactNo) {
        HashMap<String, AttributeValue> expressionAttributeValues = new HashMap<>();
        expressionAttributeValues.put(":contactNo", new AttributeValue().withS(contactNo));
        DynamoDBQueryExpression<DB_Restaurant> queryExpression = new DynamoDBQueryExpression<DB_Restaurant>()
                .withIndexName("contactNo-index")
                .withKeyConditionExpression("contactNo = :contactNo")
                .withExpressionAttributeValues(expressionAttributeValues).withConsistentRead(false);
        PaginatedQueryList<DB_Restaurant> dbQueryList = AWSCredentials.dynamoDBMapper().query(DB_Restaurant.class,
                queryExpression);
        return (dbQueryList != null && dbQueryList.size() > 0) ? dbQueryList.get(0) : null;
    }
    public static DB_Restaurant fetchRestaurantByEmailId(String emailId) {
        HashMap<String, AttributeValue> expressionAttributeValues = new HashMap<>();
        expressionAttributeValues.put(":emailId", new AttributeValue().withS(emailId));

        DynamoDBQueryExpression<DB_Restaurant> queryExpression = new DynamoDBQueryExpression<DB_Restaurant>()
                .withIndexName("emailId-index")
                .withKeyConditionExpression("emailId = :emailId")
                .withExpressionAttributeValues(expressionAttributeValues)
                .withConsistentRead(false);

        PaginatedQueryList<DB_Restaurant> dbQueryList =
                AWSCredentials.dynamoDBMapper().query(DB_Restaurant.class, queryExpression);

        return (dbQueryList != null && dbQueryList.size() > 0) ? dbQueryList.get(0) : null;
    }


    public static  PaginatedQueryList<DB_Restaurant> fetchByCity(String city) {
        HashMap<String, AttributeValue> expressionAttributeValues = new HashMap<>();
        expressionAttributeValues.put(":city", new AttributeValue().withS(city));
        DynamoDBQueryExpression<DB_Restaurant> queryExpression = new DynamoDBQueryExpression<DB_Restaurant>()
                .withIndexName("city-index")
                .withKeyConditionExpression("city = :city")
                .withExpressionAttributeValues(expressionAttributeValues).withConsistentRead(false);
        PaginatedQueryList<DB_Restaurant> dbQueryList = AWSCredentials.dynamoDBMapper().query(DB_Restaurant.class,
                queryExpression);
        return (dbQueryList != null && dbQueryList.size() > 0) ? dbQueryList : null;

    }
    @Getter @Setter @NoArgsConstructor @AllArgsConstructor
    public static class BasicInfo {
        private String restaurantName;
        private String contactNumber;
        private String emailId;


    }

    @Getter @Setter @NoArgsConstructor @AllArgsConstructor
    public static class ProfileInfo {
        private String[] cuisineTypes;
        private Integer seatingCapacity;
        private OperatingHours operatingHours;
        private String[] serviceTypes;
        private String customCuisine;

    }


    @Getter @Setter @NoArgsConstructor @AllArgsConstructor
    public static class OperatingHours {
        private String openingTime;
        private String closingTime;


    }

    @Getter @Setter @NoArgsConstructor @AllArgsConstructor
    public static class AddressInfo {

        private Double latitude;
        private Double longitude;
    }

    @Getter @Setter @NoArgsConstructor @AllArgsConstructor
    public static class BankDetails {
        private String AccountNumber;
        private String ifscCode;
        private String accountHolderName;
        private String bankName;
    }
}
