package org.turbofinn.dbmappers;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import lombok.*;
import org.turbofinn.aws.AWSCredentials;

import java.util.HashMap;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName = "Table")
public class DB_Table {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String tableId;

    @DynamoDBAttribute
    private String tableNo;

    @DynamoDBAttribute
    private String restaurantId;

    @DynamoDBAttribute
    private String userId;

    public void save() {
//        if (this.tableId == null) {
//            throw new IllegalArgumentException("Table ID cannot be null");
//        }
        AWSCredentials.dynamoDBMapper().save(this);
        System.out.println("*** Table Saved *** " + this.toString());
    }

    public static DB_Table fetchByTableId(String tableId) {
        if (tableId == null) {
            throw new IllegalArgumentException("Table ID cannot be null");
        }
        return AWSCredentials.dynamoDBMapper().load(DB_Table.class, tableId);
    }

    public static List<DB_Order> fetchOrderDetailsByTableNo(String tableNo, String restaurantId, String userId) {
        HashMap<String, AttributeValue> expressionAttributeValues = new HashMap<>();
        expressionAttributeValues.put(":tableNo", new AttributeValue().withS(tableNo));
        expressionAttributeValues.put(":restaurantId", new AttributeValue().withS(restaurantId));
        expressionAttributeValues.put(":userId", new AttributeValue().withS(userId));

        DynamoDBQueryExpression<DB_Order> queryExpression = new DynamoDBQueryExpression<DB_Order>()
                .withIndexName("tableNo-index")
                .withKeyConditionExpression("tableNo = :tableNo")
                .withFilterExpression("restaurantId = :restaurantId and userId = :userId")
                .withExpressionAttributeValues(expressionAttributeValues)
                .withConsistentRead(false);

        return AWSCredentials.dynamoDBMapper().query(DB_Order.class, queryExpression);
    }
}
