package org.turbofinn.dbmappers;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.gson.Gson;
import lombok.*;
import org.turbofinn.aws.AWSCredentials;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@DynamoDBTable(tableName = "User")
public class DB_User extends DB_DateTable{

    public static void main(String[] args) {
        DB_User dbUser = new DB_User();
        dbUser.setUserName("Sarthak");
        dbUser.setEmail("sarthak55@gmail.com");
        dbUser.setMobileNo("7985157963");
        dbUser.setDob("2024-01-01");
        dbUser.setProfilePicture("sdfgfb.jpeg");
        dbUser.setGender("Female");
        dbUser.save();
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    String userId;
    String userName;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "mobileNo-index")
    String mobileNo;
    String email;
    String gender;
    String dob;
    String profilePicture;


    public void save() {
        AWSCredentials.dynamoDBMapper().save(this);
        System.out.println("*** User Saved *** " + new Gson().toJson(this));
    }

}
